server {
    listen 80;
    
    # La cartella dove Nginx trova i file generati da Vite
    root /usr/share/nginx/html;
    index index.html;

    # Se un percorso non esiste fisicamente, reindirizza tutto a index.html (regola d'oro per le SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Opzionale: Nasconde la versione di Nginx per sicurezza
    server_tokens off;
}