apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: campus-ingress
  namespace: default
  annotations:
    # Specifica che stiamo usando NGINX come Ingress Controller 
    kubernetes.io/ingress.class: "nginx"
    
    # Aumentiamo il limite di upload per permettere l'invio delle foto al Media Service!
    nginx.ingress.kubernetes.io/proxy-body-size: "50m" 
spec:
  rules:
  - host: 192.168.72.109.nip.io  
    http:
      paths:
      # Regola 1: Tutte le chiamate che iniziano con /api vanno all'API Gateway
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway-service
            port:
              number: 5000
              
      # (Opzionale per il futuro) Regola 2: Il resto va al Frontend
      # - path: /
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: frontend-service
      #       port:
      #         number: 80